# Docker image from Docker Hub as your build environment.
image: microsoft/dotnet:sdk

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script:
          - git config --global core.autocrlf true
          - export ARTIFACTS_FOLDER=./.artifacts
          - export CONFIGURATION=Debug
          - dotnet --version
          # Build MalwareScan.Client
          - >-
              dotnet publish ./src/MalwareScan.Client `
                --output "$env:APPVEYOR_BUILD_FOLDER/.artifacts/MalwareScan.Client/fdd" `
                --configuration "$env:CONFIGURATION"

          # Pack MalwareScan.Client
          - >-
              dotnet pack ./src/MalwareScan.Client `
                --output "$env:APPVEYOR_BUILD_FOLDER/.artifacts" `
                --configuration "$env:CONFIGURATION"

          # Build MalwareScan.ClientApp (framework-dependend deployment)
          - >-
              dotnet publish ./src/MalwareScan.ClientApp `
                --output "$env:APPVEYOR_BUILD_FOLDER/.artifacts/MalwareScan.ClientApp/fdd" `
                --configuration "$env:CONFIGURATION"

          # Build MalwareScan.ClientApp for win-x86
          - >-
              dotnet publish ./src/MalwareScan.ClientApp `
                --output "$env:APPVEYOR_BUILD_FOLDER/.artifacts/MalwareScan.ClientApp/win-x86" `
                --configuration "$env:CONFIGURATION" `
                --runtime "win-x86"

          # Build MalwareScan.ClientApp for win-x64
          - >-
              dotnet publish ./src/MalwareScan.ClientApp `
                --output "$env:APPVEYOR_BUILD_FOLDER/.artifacts/MalwareScan.ClientApp/win-x64" `
                --configuration "$env:CONFIGURATION" `
                --runtime "win-x64"

          # Build MalwareScan.ClientApp for linux-x64
          - >-
              dotnet publish ./src/MalwareScan.ClientApp `
                --output "$env:APPVEYOR_BUILD_FOLDER/.artifacts/MalwareScan.ClientApp/linux-x64" `
                --configuration "$env:CONFIGURATION" `
                --runtime "linux-x64"

          # MalwareScan.Client unit tests
          - >-
              dotnet test test/MalwareScan.Client.UnitTests `
                --configuration "$env:CONFIGURATION" `
                --collect "Code Coverage"

          # MalwareScan.ClientApp unit tests
          - >-
              dotnet test test/MalwareScan.ClientApp.UnitTests `
                --configuration "$env:CONFIGURATION" `
                --collect "Code Coverage"
